### ISSUE TITLE
 File "/usr/lib/python2.7/site-packages/sentry/eventstream/snuba.py", line 239, in _send     raise snuba.SnubaError(err) SnubaError: None: Max retries exceeded with url: /tests/events/eventstream (Caused by None)

### ISSUE THREAD

**Issue by nju-Nicko** [getsentry/sentry-docs#1564]
Hello, i'm installing Sentry10 using pip on CentOS7.7. And now I have finished the installing and i can successfully run the `sentry web` and `sentry cron` and I can successfully login Sentry by sentry web. However, when i use `sentry run worker` to start the worker, error occurred as below:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 169, in _inner
    reraise(*exc_info)
  File "/usr/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 164, in _inner
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/sentry/tasks/base.py", line 48, in _wrapped
    result = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/sentry/tasks/store.py", line 660, in save_event
    _do_save_event(cache_key, data, start_time, event_id, project_id, **kwargs)
  File "/usr/lib/python2.7/site-packages/sentry/tasks/store.py", line 591, in _do_save_event
    event = manager.save(project_id, assume_normalized=True)
  File "/usr/lib/python2.7/site-packages/sentry/event_manager.py", line 777, in save
    skip_consume=raw,
  File "/usr/lib/python2.7/site-packages/sentry/utils/services.py", line 104, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/usr/lib/python2.7/site-packages/sentry/eventstream/snuba.py", line 261, in insert
    skip_consume,
  File "/usr/lib/python2.7/site-packages/sentry/eventstream/snuba.py", line 125, in insert
    "skip_consume": skip_consume,
  File "/usr/lib/python2.7/site-packages/sentry/eventstream/snuba.py", line 239, in _send
    raise snuba.SnubaError(err)
SnubaError: None: Max retries exceeded with url: /tests/events/eventstream (Caused by None)
01:19:30 [ERROR] celery.worker.job: Task sentry.tasks.store.save_event[6f38920c-2bac-43a1-abc2-a28647ca9389] raised unexpected: SnubaError(MaxRetryError('None: Max retries exceeded with url: /tests/events/eventstream (Caused by None)',),) (data={u'hostname': 'celery@em-188', u'name': 'sentry.tasks.store.save_event', u'args': '[]', u'internal': False, u'kwargs': "{'event_id': u'a300820f2155455c8546f6523e26b6de', 'cache_key': u'e:a300820f2155455c8546f6523e26b6de:1', 'start_time': 1584667169.962888, 'project_id': 1L, 'data': None}", u'id': '6f38920c-2bac-43a1-abc2-a28647ca9389'})
```
and the web page of Issues has problems as below:
![image](https://user-images.githubusercontent.com/7032962/77133491-2e286e00-6a9e-11ea-857c-d146459192e3.png)
Here is the error thrown by sentry web:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sentry/api/base.py", line 89, in handle_exception
    response = super(Endpoint, self).handle_exception(exc)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 434, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/lib/python2.7/site-packages/sentry/api/base.py", line 196, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/sentry/api/endpoints/organization_group_index.py", line 176, in get
    {"count_hits": True, "date_to": end, "date_from": start},
  File "/usr/lib/python2.7/site-packages/sentry/api/endpoints/organization_group_index.py", line 45, in _search
    result = search.query(**query_kwargs)
  File "/usr/lib/python2.7/site-packages/sentry/search/snuba/backend.py", line 181, in query
    date_to=date_to,
  File "/usr/lib/python2.7/site-packages/sentry/search/snuba/executors.py", line 405, in query
    search_filters=search_filters,
  File "/usr/lib/python2.7/site-packages/sentry/search/snuba/executors.py", line 193, in snuba_search
    sample=1,  # Don't use clickhouse sampling, even when in turbo mode.
  File "/usr/lib/python2.7/site-packages/sentry/utils/snuba.py", line 1106, in dataset_query
    **kwargs
  File "/usr/lib/python2.7/site-packages/sentry/utils/snuba.py", line 812, in raw_query
    return bulk_raw_query([snuba_params], referrer=referrer)[0]
  File "/usr/lib/python2.7/site-packages/sentry/utils/snuba.py", line 841, in bulk_raw_query
    query_results = [snuba_query(query_param_list[0])]
  File "/usr/lib/python2.7/site-packages/sentry/utils/snuba.py", line 834, in snuba_query
    raise SnubaError(err)
SnubaError: HTTPConnectionPool(host='localhost', port=1218): Max retries exceeded with url: /query (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f750458ff50>: Failed to establish a new connection: [Errno 111] Connection refused',))
```
**Can anybody help me to figure out?**

**Comment by githubmann** [comment]
Can anybody help me to figure out too?

**Comment by nju-Nicko** [comment]
> Can anybody help me to figure out too?
