### ISSUE TITLE
Don't require PostgreSQL

### ISSUE THREAD

**Issue by asbjornu** [getsentry/sentry-docs#28]
If PostgreSQL isn't installed, `make build` fails with the following output:

```
Collecting psycopg2<2.6.0,>=2.5.0 (from sentry[dev])
  Using cached psycopg2-2.5.5.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    Error: pg_config executable not found.

    Please add the directory containing pg_config to the PATH
    or specify the full executable path with the option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_t/hkn5jvjd6blcf9tf8zv5cx8c0000gn/T/pip-build-ePGMVA/psycopg2
Traceback (most recent call last):
  File "./bin/../doc-modules/sentry/api-docs/generator.py", line 6, in <module>
    import click
ImportError: No module named click
Traceback (most recent call last):
  File "./bin/../doc-modules/sentry/bin/dump-command-help", line 3, in <module>
    import click
ImportError: No module named click
Makefile:52: recipe for target 'extract-docs' failed
make: *** [extract-docs] Error 1
```

Why would building documentation require PostgreSQL? Doing `brew install postgresql` fixed that part of the build (though it failed for another reason later), but it would be nice not requiring PostgreSQL just to convert some `.rst` files to HTML.

**Comment by mitsuhiko** [comment]
The federated documentation for this command runs the API tests which pull in all sentry dependencies for development which also depends on postgres. This is intentional.

**Comment by asbjornu** [comment]
@mitsuhiko Weird, but ok.
