### ISSUE TITLE
Build fails with "Unable to fetch local project" error

### ISSUE THREAD

**Issue by asbjornu** [getsentry/sentry-docs#29]
When doing `make build`, it fails with the following output:

```
[2016-01-14 15:09:16] redis: Launching redis server
[ERROR] Unable to fetch internal project
Traceback (most recent call last):
  File "./doc-modules/sentry/src/sentry/utils/raven.py", line 59, in send
    project = Project.objects.get_from_cache(id=settings.SENTRY_PROJECT)
  File "./doc-modules/sentry/src/sentry/db/models/manager.py", line 259, in get_from_cache
    result = self.get(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 452, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: sentry_project
Traceback (most recent call last):
  File "./bin/../doc-modules/sentry/api-docs/generator.py", line 218, in <module>
    cli()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "./bin/../doc-modules/sentry/api-docs/generator.py", line 154, in cli
    with SentryBox():
  File "./bin/../doc-modules/sentry/api-docs/generator.py", line 112, in __enter__
    self.redis = launch_redis()
  File "./bin/../doc-modules/sentry/api-docs/generator.py", line 56, in launch_redis
    cl = Popen(['redis-server', '-'], stdin=PIPE, stdout=open(os.devnull, 'r+'))
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
--> Generate API documentation
./bin/generate-api-docs
Traceback (most recent call last):
  File "./bin/generate-api-docs", line 165, in <module>
    cli()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "./bin/generate-api-docs", line 156, in cli
    for section in iter_sections():
  File "./bin/generate-api-docs", line 42, in iter_sections
    with open(os.path.join(API_CACHE, 'sections.json')) as f:
IOError: [Errno 2] No such file or directory: './docs/_apicache/sections.json'
Makefile:56: recipe for target 'generate-api-docs' failed
make: *** [generate-api-docs] Error 1
```

Why is redis required to build the documentation? What's going on here?

**Comment by asbjornu** [comment]
There's also this error occurring directly after the `make build` command:

```
--> Update api-docs venv
./bin/extract-docs
./bin/extract-docs: line 7: virtualenv: command not found
./bin/extract-docs: line 8: ./bin/../.api-docs-venv/bin/activate: No such file or directory
```

**Comment by mitsuhiko** [comment]
You are missing virtualenv as command. It's required to build this documentation.

May I ask why you are trying to build the docs? The setup is quite involved.

**Comment by asbjornu** [comment]
@mitsuhiko As you see in my last comment, I've already installed `virtalenv` and it still fails. I want to build the documentation so I can test changes made to `index.rst` and such before merging to master.

Also, shouldn't `virtualenv` exist as a requirement so it can be installed with the rest of the Python modules?

**Comment by mitsuhiko** [comment]
I will try to improve the docs to manage the virtualenvs more.

**Comment by asbjornu** [comment]
@mitsuhiko Thanks!

**Comment by mitsuhiko** [comment]
This uses a local venv now.

**Comment by asbjornu** [comment]
@mitsuhiko Thanks, but `make build` still fails with "Unable to fetch internal project":

```python
[2016-01-25 09:54:21] redis: Launching redis server
[ERROR] Unable to fetch internal project
Traceback (most recent call last):
  File "./doc-modules/sentry/src/sentry/utils/raven.py", line 59, in send
    project = Project.objects.get_from_cache(id=settings.SENTRY_PROJECT)
  File "./doc-modules/sentry/src/sentry/db/models/manager.py", line 259, in get_from_cache
    result = self.get(**kwargs)
  File "./.api-docs-venv/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "./.api-docs-venv/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "./.api-docs-venv/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "./.api-docs-venv/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "./.api-docs-venv/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "./.api-docs-venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "./.api-docs-venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "./.api-docs-venv/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "./.api-docs-venv/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "./.api-docs-venv/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "./.api-docs-venv/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "./.api-docs-venv/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 452, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: sentry_project
Traceback (most recent call last):
  File "./bin/../doc-modules/sentry/api-docs/generator.py", line 218, in <module>
    cli()
  File "./.api-docs-venv/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "./.api-docs-venv/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "./.api-docs-venv/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "./.api-docs-venv/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "./bin/../doc-modules/sentry/api-docs/generator.py", line 154, in cli
    with SentryBox():
  File "./bin/../doc-modules/sentry/api-docs/generator.py", line 112, in __enter__
    self.redis = launch_redis()
  File "./bin/../doc-modules/sentry/api-docs/generator.py", line 56, in launch_redis
    cl = Popen(['redis-server', '-'], stdin=PIPE, stdout=open(os.devnull, 'r+'))
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
--> Generate API documentation
./venv/bin/python ./bin/generate-api-docs
Traceback (most recent call last):
  File "./bin/generate-api-docs", line 6, in <module>
    import click
ImportError: No module named click
Makefile:61: recipe for target 'generate-api-docs' failed
make: *** [generate-api-docs] Error 1
```
