### ISSUE TITLE
Update node-sass

### ISSUE THREAD

**Issue by kevinrenskers** [getsentry/sentry-docs#5936]
### Steps to Reproduce

When I ran `bin/bootstrap` I first ran into the issue that I didn't have Yarn installed, which I had to do manually. This is not documented in https://docs.sentry.io/contributing/environment/, and not part of the bootstrap script.

After installing Yarn, I ran `bin/bootstrap` but now I ran into this error:

```
error /Users/kevin/Workspace/sentry-docs/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: /Users/kevin/Workspace/sentry-docs/node_modules/node-sass
Output:
Building: /Users/kevin/Library/pnpm/nodejs/16.17.0/bin/node /Users/kevin/Workspace/sentry-docs/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/Users/kevin/Library/pnpm/nodejs/16.17.0/bin/node',
gyp verb cli   '/Users/kevin/Workspace/sentry-docs/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@16.17.0 | darwin | arm64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/kevin/Workspace/sentry-docs/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/kevin/Workspace/sentry-docs/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/kevin/Workspace/sentry-docs/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/kevin/Workspace/sentry-docs/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/kevin/Workspace/sentry-docs/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/kevin/Workspace/sentry-docs/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:206:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/kevin/Workspace/sentry-docs/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/kevin/Workspace/sentry-docs/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/kevin/Workspace/sentry-docs/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/kevin/Workspace/sentry-docs/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/kevin/Workspace/sentry-docs/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/kevin/Workspace/sentry-docs/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:206:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /opt/homebrew/opt/python@3.10/libexec/bin/python
gyp ERR! configure error
gyp ERR! stack Error: Command failed: /opt/homebrew/opt/python@3.10/libexec/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:400:12)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1093:16)
gyp ERR! stack     at Socket.<anonymous> (node:internal/child_process:451:11)
gyp ERR! stack     at Socket.emit (node:events:513:28)
gyp ERR! stack     at Pipe.<anonymous> (node:net:757:14)
gyp ERR! System Darwin 22.1.0
gyp ERR! command "/Users/kevin/Library/pnpm/nodejs/16.17.0/bin/node" "/Users/kevin/Workspace/sentry-docs/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/kevin/Workspace/sentry-docs/node_modules/node-sass
gyp ERR! node -v v16.17.0
```

I found https://github.com/nodejs/node-gyp/tree/main/docs and it turns out that sentry-docs is using an ancient version of node-gyp, due to it depending on node-sass v4, which is really old.

Updating node-sass to `^8.0.0` in package.json solved the problem, and after running `bin/bootstrap` again it now completed without issue. But then running `yarn start` gives these errors:

```
ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Node Sass version 8.0.0 is incompatible with ^4.0.0.

File: src/css/screen.scss

failed Building development bundle - 6.457s
```

### Expected Result

I should be able to build and run sentry-docs locally.

### Actual Result

See steps to reproduce.

### Additional Info

I'm on an M1 Macbook Pro.

**Comment by kevinrenskers** [comment]
Found a solution:

```
yarn remove node-sass
yarn add sass
```

node-sass has been deprecated for some time now.

And now `yarn start` does run successfully - although with a bunch of Sass related deprecation warnings.
